"""
initial

Revision ID: 001_initial
Revises: 
Create Date: 2024-05-18 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    op.create_table('document_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_groups_user_id'), 'document_groups', ['user_id'], unique=False)
    
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('stored_filename', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.Enum('PDF', 'JPG', 'PNG', name='file_type_enum'), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'PARTIALLY_PROCESSED', 'FAILED', name='document_status_enum'), nullable=False),
    sa.Column('is_answer_key', sa.Boolean(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['document_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_documents_group_id'), 'documents', ['group_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('question_number', sa.String(length=50), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('MCQ', 'TRUE_FALSE', 'SHORT_ANSWER', 'LONG_ANSWER', 'FILL_IN_BLANK', 'MATCH', 'UNKNOWN', name='question_type_enum'), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answer_source', sa.Enum('SAME_DOCUMENT', 'LINKED_DOCUMENT', 'NOT_FOUND', 'UNMATCHED', name='answer_source_enum'), nullable=False),
    sa.Column('answer_confidence', sa.Float(), nullable=False),
    sa.Column('source_pages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_cross_page', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_status', sa.Enum('EXTRACTED', 'PARTIAL', 'REVIEW_REQUIRED', name='extraction_status_enum'), nullable=False),
    sa.Column('has_image', sa.Boolean(), nullable=False),
    sa.Column('has_table', sa.Boolean(), nullable=False),
    sa.Column('extraction_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_document_id'), 'questions', ['document_id'], unique=False)
    op.create_index(op.f('ix_questions_extraction_status'), 'questions', ['extraction_status'], unique=False)
    
    op.create_table('extraction_warnings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('warning_type', sa.Enum('LOW_CONFIDENCE', 'OCR_ERROR', 'MISSING_NUMBER', 'CROSS_PAGE', 'UNCLEAR_ANSWER', 'UNMATCHED_ANSWER', 'INVALID_FORMAT', 'MALFORMED_FILE', 'PARTIAL_OPTIONS', 'BLURRY_IMAGE', 'OTHER', name='warning_type_enum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_warnings_document_id'), 'extraction_warnings', ['document_id'], unique=False)
    op.create_index(op.f('ix_extraction_warnings_question_id'), 'extraction_warnings', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_warnings_question_id'), table_name='extraction_warnings')
    op.drop_index(op.f('ix_extraction_warnings_document_id'), table_name='extraction_warnings')
    op.drop_table('extraction_warnings')
    op.drop_index(op.f('ix_questions_extraction_status'), table_name='questions')
    op.drop_index(op.f('ix_questions_document_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_group_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_document_groups_user_id'), table_name='document_groups')
    op.drop_table('document_groups')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    
    sa.Enum(name='file_type_enum').drop(op.get_bind())
    sa.Enum(name='document_status_enum').drop(op.get_bind())
    sa.Enum(name='question_type_enum').drop(op.get_bind())
    sa.Enum(name='answer_source_enum').drop(op.get_bind())
    sa.Enum(name='extraction_status_enum').drop(op.get_bind())
    sa.Enum(name='warning_type_enum').drop(op.get_bind())
    # ### end Alembic commands ###
